version: 1.0.{build}
image: Visual Studio 2019
clone_depth: 1
build_script:
- cmd: >-
    dotnet publish --configuration Release --framework netcoreapp3.1 --output "./build/" -p:PublishReadyToRun=true -p:PublishSingleFile=true --no-self-contained --runtime win-x64
test: off
artifacts:
- path: build\
  name: FModel
